### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by jonathan-potter** [blaze33/way-of-life#1]
Hey, I cloned this and had to `npm install` `glob` and `fs` to get it working. You should add those to your `package.json`

**Comment by blaze33** [comment]
Thanks for the feedback, I'll get around this as soon as I can.

**Comment by blaze33** [comment]
Fixed in https://github.com/blaze33/way-of-life/commit/288ff1d9585af6541498a8ed60236c98ec2a54f8
