### ISSUE TITLE
Demo not work on Safari iOS 10

### ISSUE THREAD

**Issue by nvcken** [blaze33/way-of-life#3]
Does it not support on Safari iOS ?

**Comment by blaze33** [comment]
Alas, WebAssembly support was only added in Safari 11, cf. https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html
I suppose it should be possible to have an asm.js fallback when wasm is not supported but I don't have an iOS device to test this...
